@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "boat.Boat#getPrice()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "boat.Boat",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3029312 { 
   	label=boat
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1599376050 { 
   	label=Boat
	labeljust=l
	fillcolor=white
	style=filled
   
   Boat3029312XXXcompareTo2076000[
	label="+ compareTo()"
	style=filled
	fillcolor=white
	tooltip="Boat

&#10;  @param o the object to be compared.&#10;  @return&#10; "
	fontcolor=darkgreen
];

Boat3029312XXXgetPrice0[
	label="+ getPrice()"
	style=filled
	fillcolor=white
	tooltip="Boat

&#10;  @return&#10; "
	penwidth=4
	fontcolor=darkgreen
];

Boat3029312XXXhashCode0[
	label="+ hashCode()"
	style=filled
	fillcolor=white
	tooltip="Boat

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_347208044 { 
   	label=backend
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_228751435 { 
   	label=Database
	labeljust=l
	fillcolor=white
	style=filled
   
   Database347208044XXXDatabase1221374297[
	label="+ Database()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXaddBoat2076000[
	label="+ addBoat()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXdeleteBoat2076000[
	label="+ deleteBoat()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXgetAveragePrice1808118735[
	label="+ getAveragePrice()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshow0[
	label="+ show()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowAllBoats0[
	label="+ showAllBoats()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsByLengthRange543312618[
	label="+ showBoatsByLengthRange()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsByMake1808118735[
	label="+ showBoatsByMake()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsByPriceRange543312618[
	label="+ showBoatsByPriceRange()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsByRegion1808118735[
	label="+ showBoatsByRegion()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsByVariant1808118735[
	label="+ showBoatsByVariant()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsByYear104431[
	label="+ showBoatsByYear()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsByYearRange543312618[
	label="+ showBoatsByYearRange()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsByrPrice1325958191[
	label="+ showBoatsByrPrice()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsBysPrice1325958191[
	label="+ showBoatsBysPrice()"
	style=filled
	fillcolor=white
	tooltip="Database

null"
	fontcolor=darkgreen
];

Database347208044XXXshowBoatsBysPriceAndMake1025473162[
	label="+ showBoatsBysPriceAndMake()"
	style=filled
	fillcolor=white
	tooltip="Database

&#10;  This method is to show the boats by make and find the price that is less than the condition&#10; &#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_834648217 { 
   	label=Menu
	labeljust=l
	fillcolor=white
	style=filled
   
   Menu347208044XXXrecommendBoat0[
	label="+ recommendBoat()"
	style=filled
	fillcolor=white
	tooltip="Menu

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
Boat3029312XXXcompareTo2076000 -> Boat3029312XXXgetPrice0;
Boat3029312XXXhashCode0 -> Boat3029312XXXgetPrice0;
Database347208044XXXDatabase1221374297 -> Boat3029312XXXgetPrice0;
Database347208044XXXaddBoat2076000 -> Boat3029312XXXgetPrice0;
Database347208044XXXdeleteBoat2076000 -> Boat3029312XXXgetPrice0;
Database347208044XXXgetAveragePrice1808118735 -> Boat3029312XXXgetPrice0;
Database347208044XXXshow0 -> Database347208044XXXshowAllBoats0;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsByLengthRange543312618;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsByMake1808118735;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsByPriceRange543312618;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsByRegion1808118735;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsByVariant1808118735;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsByYear104431;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsByYearRange543312618;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsByrPrice1325958191;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsBysPrice1325958191;
Database347208044XXXshow0 -> Database347208044XXXshowBoatsBysPriceAndMake1025473162;
Database347208044XXXshowAllBoats0 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsByLengthRange543312618 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsByMake1808118735 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsByPriceRange543312618 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsByRegion1808118735 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsByVariant1808118735 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsByYear104431 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsByYearRange543312618 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsByrPrice1325958191 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsBysPrice1325958191 -> Boat3029312XXXgetPrice0;
Database347208044XXXshowBoatsBysPriceAndMake1025473162 -> Boat3029312XXXgetPrice0;
Menu347208044XXXrecommendBoat0 -> Database347208044XXXshow0;
    
}
@enduml